spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver